USE PACT2C222
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spADM_GetPriceChartLatestData]
	@PriceXML [nvarchar](max) = null,
	@UserID [bigint],
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRANSACTION  
BEGIN TRY  
SET NOCOUNT ON;
	--Declaration Section  
	DECLARE @XML XML
	DECLARE @TblXML TABLE(ID INT,ProductID BIGINT,UOMID BIGINT,AccountID BIGINT
	    ,PurchaseRate FLOAT,PurchaseRateA FLOAT,PurchaseRateB FLOAT,PurchaseRateC FLOAT,PurchaseRateD FLOAT,PurchaseRateE FLOAT,PurchaseRateF FLOAT,PurchaseRateG FLOAT
	    ,SellingRate FLOAT,SellingRateA FLOAT,SellingRateB FLOAT,SellingRateC FLOAT,SellingRateD FLOAT,SellingRateE FLOAT,SellingRateF FLOAT,SellingRateG FLOAT
        ,ReorderLevel FLOAT,ReorderQty FLOAT
	   ,CCNID1 BIGINT,CCNID2 BIGINT,CCNID3 BIGINT,CCNID4 BIGINT,CCNID5 BIGINT,CCNID6 BIGINT,CCNID7 BIGINT,CCNID8 BIGINT,CCNID9 BIGINT,CCNID10 BIGINT
       ,CCNID11 BIGINT,CCNID12 BIGINT,CCNID13 BIGINT,CCNID14 BIGINT,CCNID15 BIGINT,CCNID16 BIGINT,CCNID17 BIGINT,CCNID18 BIGINT,CCNID19 BIGINT,CCNID20 BIGINT
       ,CCNID21 BIGINT,CCNID22 BIGINT,CCNID23 BIGINT,CCNID24 BIGINT,CCNID25 BIGINT,CCNID26 BIGINT,CCNID27 BIGINT,CCNID28 BIGINT,CCNID29 BIGINT,CCNID30 BIGINT
       ,CCNID31 BIGINT,CCNID32 BIGINT,CCNID33 BIGINT,CCNID34 BIGINT,CCNID35 BIGINT,CCNID36 BIGINT,CCNID37 BIGINT,CCNID38 BIGINT,CCNID39 BIGINT,CCNID40 BIGINT
       ,CCNID41 BIGINT,CCNID42 BIGINT,CCNID43 BIGINT,CCNID44 BIGINT,CCNID45 BIGINT,CCNID46 BIGINT,CCNID47 BIGINT,CCNID48 BIGINT,CCNID49 BIGINT,CCNID50 BIGINT)

	SET @XML=@PriceXML
	
	INSERT INTO @TblXML(ID,[ProductID],UOMID,AccountID
	   ,CCNID1,CCNID2,CCNID3,CCNID4,CCNID5,CCNID6,CCNID7,CCNID8,CCNID9,CCNID10
	   ,CCNID11,CCNID12,CCNID13,CCNID14,CCNID15,CCNID16,CCNID17,CCNID18,CCNID19,CCNID20
       ,CCNID21,CCNID22,CCNID23,CCNID24,CCNID25,CCNID26,CCNID27,CCNID28,CCNID29,CCNID30
       ,CCNID31,CCNID32,CCNID33,CCNID34,CCNID35,CCNID36,CCNID37,CCNID38,CCNID39,CCNID40
       ,CCNID41,CCNID42,CCNID43,CCNID44,CCNID45,CCNID46,CCNID47,CCNID48,CCNID49,CCNID50)
	SELECT X.value('@ID','INT'), ISNULL(X.value('@ProductID','BIGINT'),1),ISNULL(X.value('@UOMID','BIGINT'),1),ISNULL(X.value('@AccountID','BIGINT'),0),
		ISNULL(X.value('@CC1','BIGINT'),0),ISNULL(X.value('@CC2','BIGINT'),0),ISNULL(X.value('@CC3','BIGINT'),0),ISNULL(X.value('@CC4','BIGINT'),0),ISNULL(X.value('@CC5','BIGINT'),0),ISNULL(X.value('@CC6','BIGINT'),0),ISNULL(X.value('@CC7','BIGINT'),0),ISNULL(X.value('@CC8','BIGINT'),0),ISNULL(X.value('@CC9','BIGINT'),0),ISNULL(X.value('@CC10','BIGINT'),0),
		ISNULL(X.value('@CC11','BIGINT'),0),ISNULL(X.value('@CC12','BIGINT'),0),ISNULL(X.value('@CC13','BIGINT'),0),ISNULL(X.value('@CC14','BIGINT'),0),ISNULL(X.value('@CC15','BIGINT'),0),ISNULL(X.value('@CC16','BIGINT'),0),ISNULL(X.value('@CC17','BIGINT'),0),ISNULL(X.value('@CC18','BIGINT'),0),ISNULL(X.value('@CC19','BIGINT'),0),ISNULL(X.value('@CC20','BIGINT'),0),
		ISNULL(X.value('@CC21','BIGINT'),0),ISNULL(X.value('@CC22','BIGINT'),0),ISNULL(X.value('@CC23','BIGINT'),0),ISNULL(X.value('@CC24','BIGINT'),0),ISNULL(X.value('@CC25','BIGINT'),0),ISNULL(X.value('@CC26','BIGINT'),0),ISNULL(X.value('@CC27','BIGINT'),0),ISNULL(X.value('@CC28','BIGINT'),0),ISNULL(X.value('@CC29','BIGINT'),0),ISNULL(X.value('@CC30','BIGINT'),0),
		ISNULL(X.value('@CC31','BIGINT'),0),ISNULL(X.value('@CC32','BIGINT'),0),ISNULL(X.value('@CC33','BIGINT'),0),ISNULL(X.value('@CC34','BIGINT'),0),ISNULL(X.value('@CC35','BIGINT'),0),ISNULL(X.value('@CC36','BIGINT'),0),ISNULL(X.value('@CC37','BIGINT'),0),ISNULL(X.value('@CC38','BIGINT'),0),ISNULL(X.value('@CC39','BIGINT'),0),ISNULL(X.value('@CC40','BIGINT'),0),
		ISNULL(X.value('@CC41','BIGINT'),0),ISNULL(X.value('@CC42','BIGINT'),0),ISNULL(X.value('@CC43','BIGINT'),0),ISNULL(X.value('@CC44','BIGINT'),0),ISNULL(X.value('@CC45','BIGINT'),0),ISNULL(X.value('@CC46','BIGINT'),0),ISNULL(X.value('@CC47','BIGINT'),0),ISNULL(X.value('@CC48','BIGINT'),0),ISNULL(X.value('@CC49','BIGINT'),0),ISNULL(X.value('@CC50','BIGINT'),0)			
	FROM @XML.nodes('/XML/Row') as Data(X)
	
	DECLARE @I INT,@CNT INT,@PriceCCID BIGINT
	SELECT @I=1,@CNT=COUNT(*) FROM @TblXML
	   
	WHILE(@I<=@CNT)
	BEGIN
 
  		SELECT TOP 1 @PriceCCID=PriceCCID
		FROM COM_CCPrices P
		INNER JOIN @TblXML X ON X.ProductID=P.ProductID AND X.UOMID=P.UOMID AND X.AccountID=P.AccountID
		WHERE X.ID=@I AND X.CCNID1=P.CCNID1 AND X.CCNID2=P.CCNID2 AND X.CCNID3=P.CCNID3 AND X.CCNID4=P.CCNID4
			AND X.CCNID5=P.CCNID5 AND X.CCNID6=P.CCNID6 AND X.CCNID7=P.CCNID7 AND X.CCNID8=P.CCNID8
		ORDER BY WEF DESC
		
		UPDATE @TblXML
		SET PurchaseRate=P.PurchaseRate,PurchaseRateA=P.PurchaseRateA,PurchaseRateB=P.PurchaseRateB,PurchaseRateC=P.PurchaseRateC,PurchaseRateD=P.PurchaseRateD,PurchaseRateE=P.PurchaseRateE,PurchaseRateF=P.PurchaseRateF,PurchaseRateG=P.PurchaseRateG
		    ,SellingRate=P.SellingRate,SellingRateA=P.SellingRateA,SellingRateB=P.SellingRateB,SellingRateC=P.SellingRateC,SellingRateD=P.SellingRateD,SellingRateE=P.SellingRateE,SellingRateF=P.SellingRateF,SellingRateG=P.SellingRateG
            ,ReorderLevel=P.ReorderLevel,ReorderQty=P.ReorderQty
		FROM COM_CCPrices P
		WHERE P.PriceCCID=@PriceCCID AND ID=@I
	
		SET @I=@I+1	
	END
	
	 select ID,PurchaseRate,PurchaseRateA,PurchaseRateB,PurchaseRateC,PurchaseRateD,PurchaseRateE,PurchaseRateF,PurchaseRateG
		    ,SellingRate,SellingRateA,SellingRateB,SellingRateC,SellingRateD,SellingRateE,SellingRateF,SellingRateG
            ,ReorderLevel,ReorderQty from @TblXML


COMMIT TRANSACTION  
--ROLLBACK TRANSACTION


SET NOCOUNT OFF;  
RETURN 1  
END TRY
BEGIN CATCH  
	--Return exception info [Message,Number,ProcedureName,LineNumber]  
	IF ERROR_NUMBER()=50000
	BEGIN
		SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(NOLOCK) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID
	END
	ELSE
	BEGIN
		SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine
		FROM COM_ErrorMessages WITH(NOLOCK) WHERE ErrorNumber=-999 AND LanguageID=@LangID
	END
ROLLBACK TRANSACTION
SET NOCOUNT OFF  
RETURN -999   
END CATCH
GO
