USE PACT2C222
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_AdjustmentLeaveDetails]
	@FLAG [int] = 0,
	@EMPNODE [int],
	@LEAVETYPE [int],
	@DOCID [int],
	@USERID [int] = 1,
	@LANGID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
	IF (ISNULL(@FLAG,0)=0)
	BEGIN
		IF(@DOCID =0)
		BEGIN
			--SELECT CONVERT(DATETIME,TD.DCALPHA2) FROMDATE,CONVERT(DATETIME,TD.DCALPHA3) TODATE,DN.DCNUM1 NOOFDAYS,ID.VoucherNo
		 --   FROM   INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DOCCCDATA DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
			--	   JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID JOIN COM_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
		 --   WHERE  ID.STATUSID NOT IN (372,376) AND ID.COSTCENTERID=40073 AND TD.DCALPHA5=@EMPNODE AND DC.DCCCNID52=@LEAVETYPE AND ISNULL(TD.DCALPHA4,'')='No'
		 --   UNION
			SELECT	CONVERT(DATETIME,TD.DCALPHA4) FROMDATE,CONVERT(DATETIME,TD.DCALPHA5) TODATE,TD.DCALPHA7 NOOFDAYS,ID.VoucherNo,ID.DocSeqNo DocSeqNo
			FROM    INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DOCCCDATA DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
			WHERE   ID.STATUSID =369 AND TD.tDocumentType=62 
					AND ID.VoucherNo NOT IN (SELECT ISNULL(STD.dcAlpha1,'') FROM INV_DOCDETAILS DID WITH(NOLOCK) JOIN COM_DOCTEXTDATA STD WITH(NOLOCK) ON DID.INVDOCDETAILSID=STD.INVDOCDETAILSID JOIN COM_DOCCCDATA SDC WITH(NOLOCK)ON DID.INVDOCDETAILSID=SDC.INVDOCDETAILSID 
										 WHERE DID.COSTCENTERID=40073 AND DID.STATUSID NOT IN (372,376) AND ISNULL(STD.dcAlpha4,'')='Yes'   ) 
					AND  DC.DCCCNID51=@EMPNODE AND DC.DCCCNID52=@LEAVETYPE
		END
		ELSE IF (@DOCID >0)
		BEGIN
		   --SELECT CONVERT(DATETIME,TD.DCALPHA2) FROMDATE,CONVERT(DATETIME,TD.DCALPHA3) TODATE,DN.DCNUM1 NOOFDAYS,ID.VoucherNo
		   --FROM   INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DOCCCDATA DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
				 -- JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID JOIN COM_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
		   --WHERE  ID.STATUSID NOT IN (372,376) AND ID.COSTCENTERID=40073 AND ID.DOCID=@DOCID AND TD.DCALPHA5=@EMPNODE AND DC.DCCCNID52=@LEAVETYPE
		   --UNION
		   SELECT CONVERT(DATETIME,TD.DCALPHA4) FROMDATE,CONVERT(DATETIME,TD.DCALPHA5) TODATE,TD.DCALPHA7 NOOFDAYS,ID.VoucherNo,ID.DocSeqNo DocSeqNo
		   FROM   INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DOCCCDATA DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
				  JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
		   WHERE  ID.STATUSID =369 AND TD.tDocumentType=62
			      AND ID.VoucherNo NOT IN (SELECT ISNULL(STD.dcAlpha1,'') FROM INV_DOCDETAILS DID WITH(NOLOCK) JOIN COM_DOCTEXTDATA STD WITH(NOLOCK) ON  DID.INVDOCDETAILSID=STD.INVDOCDETAILSID JOIN COM_DOCCCDATA SDC WITH(NOLOCK) ON DID.INVDOCDETAILSID=SDC.INVDOCDETAILSID
					     			   WHERE DID.COSTCENTERID=40073 AND ID.DOCID<>@DOCID AND DID.STATUSID NOT IN (372,376) AND ISNULL(STD.dcAlpha4,'')='Yes' ) 
	  			  AND DC.DCCCNID51=@EMPNODE AND DC.DCCCNID52=@LEAVETYPE
		END
	END
    
SET NOCOUNT OFF;
END


----spPAY_AdjustmentLeaveDetails 
-- 0
-- ,655
-- ,12
-- ,0
-- ,1
-- ,1
GO
