USE PACT2C222
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_SetEmployeeReleaseDate]
	@DOCID [int],
	@EMPNODE [int],
	@RESIGNDATE [datetime],
	@TENTATIVEDATE [datetime],
	@RELEASEDATE [datetime],
	@REASON [nvarchar](max)
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
	IF((SELECT COUNT(*) FROM INV_DOCDETAILS WITH(NOLOCK) WHERE DOCID=@DOCID AND STATUSID=369)>0)
	BEGIN
		UPDATE COM_CC50051 SET DORESIGN=CONVERT(FLOAT,@RESIGNDATE),DOTENTRELIEVE=CONVERT(FLOAT,@TENTATIVEDATE),
			                   DORELIEVE=CONVERT(FLOAT,@RELEASEDATE),RESIGNREMARKS=ISNULL(@REASON,'') WHERE NODEID=@EMPNODE
	END
END
GO
