USE PACT2C222
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spSVC_GetVehicleCostCenterDetails]
	@UserID [bigint],
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRANSACTION
BEGIN TRY	
SET NOCOUNT ON
 
DECLARE @FEATUREID INT, @TABLENAME VARCHAR(50), @SQL NVARCHAR(MAX)


-- To Get Color table
BEGIN 
	   
	SET @TABLENAME = (SELECT SYSTABLENAME   FROM SVC_COSTCENTER WHERE  FEATURENAME like 'Color%' )
    SET @SQL = 'SELECT * FROM ' + @TABLENAME + ' WHERE ISGROUP=0'

	EXEC (@SQL)
 	 
END
 -- To Get Fuel table
BEGIN
 	SET @TABLENAME = (SELECT SYSTABLENAME   FROM SVC_COSTCENTER WHERE  FEATURENAME like 'Fuel' )
    SET @SQL = 'SELECT * FROM ' + @TABLENAME + ' WHERE ISGROUP=0'

	EXEC (@SQL)

END 
-- To Get FUEL DELIVERY table
BEGIN
 	  
	SET @TABLENAME =(SELECT SYSTABLENAME   FROM SVC_COSTCENTER WHERE  FEATURENAME like 'Fuel Delivery' )
    SET @SQL = 'SELECT * FROM ' + @TABLENAME + ' WHERE ISGROUP=0'

	EXEC (@SQL)
END
-- To Get ENGINETYPE table
BEGIN

	  
	SET @TABLENAME = (SELECT SYSTABLENAME   FROM SVC_COSTCENTER WHERE  FEATURENAME like  'EngineType' )
    SET @SQL = 'SELECT * FROM ' + @TABLENAME + ' WHERE ISGROUP=0'

	EXEC (@SQL)
END
-- To Get Cylinder table
BEGIN
  
	SET @TABLENAME = (SELECT SYSTABLENAME   FROM SVC_COSTCENTER WHERE  FEATURENAME like  'Cylinder' )
    SET @SQL = 'SELECT * FROM ' + @TABLENAME + ' WHERE ISGROUP=0'

	EXEC (@SQL)
END
COMMIT TRANSACTION
SET NOCOUNT OFF;
RETURN 1
END TRY
BEGIN CATCH  
	--Return exception info [Message,Number,ProcedureName,LineNumber]  
	IF ERROR_NUMBER()=50000
	BEGIN
		SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID
	END
	ELSE
	BEGIN
		SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine
		FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=-999 AND LanguageID=@LangID
	END
ROLLBACK TRANSACTION
SET NOCOUNT OFF  
RETURN -999   
END CATCH  


















GO
