USE PACT2C222
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCOM_GetAssignedUserEmailAddress]
	@CostCenterID [bigint],
	@NODEID [bigint]
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRANSACTION
  
				--ASSIGNED USERS 
				DECLARE @stract NVARCHAR(MAX)
			    DECLARE @ASSIGNEDTABLE TABLE(ID INT IDENTITY(1,1),ASSIGNEDTO NVARCHAR(MAX))
			    
			    INSERT INTO @ASSIGNEDTABLE --ONLY FOR USERS
			    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN (
			    SELECT UserID FROM CRM_Assignment WITH(NOLOCK) WHERE CCID=@CostCenterID and CCNODEID=@NODEID
			    AND TEAMNODEID=0 AND ISGROUP=0 AND ISROLE=0) AND Email1 NOT IN (
			    SELECT ASSIGNEDTO FROM @ASSIGNEDTABLE ) AND (Email1<>'' AND   Email1 IS NOT NULL)
 
		 
				INSERT INTO @ASSIGNEDTABLE --ONLY FOR ROLES
			    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN (
			    SELECT UserID FROM ADM_USERROLEMAP WITH(NOLOCK) WHERE ROLEID IN (
			    SELECT TEAMNODEID FROM CRM_Assignment WITH(NOLOCK)   
			    WHERE CCID=@CostCenterID and CCNODEID=@NODEID
			    AND TEAMNODEID>0 AND ISGROUP=0 AND UserID=0 AND ISROLE=1)) AND Email1 NOT IN (
			    SELECT ASSIGNEDTO FROM @ASSIGNEDTABLE ) AND (Email1<>'' AND   Email1 IS NOT NULL)
			    
			   
			    INSERT INTO @ASSIGNEDTABLE --ONLY FOR GROUPS(ROLES)
			    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN (
			    SELECT UserID FROM ADM_USERROLEMAP WITH(NOLOCK) WHERE ROLEID IN (
			    SELECT ROLEID FROM COM_Groups WITH(NOLOCK) WHERE UserID=0 AND GID IN (
			    SELECT TEAMNODEID FROM CRM_Assignment WITH(NOLOCK)   
			    WHERE CCID=@CostCenterID and CCNODEID=@NODEID
			    AND TEAMNODEID>0 AND ISGROUP=1 AND UserID=0 AND ISROLE=0))) AND Email1 NOT IN (
			    SELECT ASSIGNEDTO FROM @ASSIGNEDTABLE ) AND (Email1<>'' AND   Email1 IS NOT NULL)
			    
			     INSERT INTO @ASSIGNEDTABLE --ONLY FOR GROUPS(USERS)
			    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN ( 
			    SELECT UserID FROM COM_Groups WITH(NOLOCK) WHERE ROLEID=0 AND GID IN (
			    SELECT TEAMNODEID FROM CRM_Assignment WITH(NOLOCK)   
			    WHERE CCID=@CostCenterID and CCNODEID=@NODEID
			    AND TEAMNODEID>0 AND ISGROUP=1 AND UserID=0 AND ISROLE=0)) AND Email1 NOT IN (
			    SELECT ASSIGNEDTO FROM @ASSIGNEDTABLE ) AND (Email1<>'' AND   Email1 IS NOT NULL)
			    
			    INSERT INTO @ASSIGNEDTABLE --ONLY FOR TEAM
			    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN ( 
			    SELECT UserID FROM crm_teams where    teamid     IN (
			    SELECT TEAMNODEID FROM CRM_Assignment WITH(NOLOCK)   
			    WHERE CCID=@CostCenterID and CCNODEID=@NODEID
			    AND TEAMNODEID>0 AND ISTEAM=1 AND ISGROUP=0 AND UserID=0 AND ISROLE=0)) AND Email1 NOT IN (
			    SELECT ASSIGNEDTO FROM @ASSIGNEDTABLE ) AND (Email1<>'' AND   Email1 IS NOT NULL)
			    
			    
			    
			    
 select @stract =coalesce(@stract , '  ' , ' ')+ Convert(varchar(50), ASSIGNEDTO)+',' from @ASSIGNEDTABLE
 if(len(@stract)>0)
	select @stract 'AssignedTo'
 else
	select null
	
COMMIT TRANSACTION    
SET NOCOUNT OFF;     
RETURN 1 



 
GO
