USE PACT2C222
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_SetEmployeeDates]
	@DOCID [int],
	@EMPNODE [int],
	@REDATE [nvarchar](100) = NULL,
	@TENTATIVEDATE [nvarchar](100) = NULL,
	@RESIGNDATE [nvarchar](100) = NULL,
	@REASON [nvarchar](max) = NULL,
	@RESIGNTYPE [nvarchar](100) = NULL,
	@USERID [int] = 1,
	@LANGID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN  
SET NOCOUNT ON;  
DECLARE @COSTCENTERID INT,@INVDOCDETAILSID INT,@STATUSID INT,@FROMDATE DATETIME,@TODATE DATETIME,@RESIGNSTATUS NVARCHAR(50)  
DECLARE @STRQRY NVARCHAR(MAX)  
SET @STRQRY=''  
  
IF ISNULL(@DOCID,0)>0  
BEGIN  
 SELECT @COSTCENTERID=COSTCENTERID,@INVDOCDETAILSID=INVDOCDETAILSID,@STATUSID=STATUSID FROM INV_DOCDETAILS WHERE DOCID=@DOCID  
 IF (@COSTCENTERID=40069)--APPLY RESIGNATION  
 BEGIN  
  SELECT @RESIGNSTATUS=STATUS FROM COM_Status WHERE STATUSID=@STATUSID  
  
  IF(@RESIGNTYPE<>'Rejected')  
  BEGIN  
   SET @STRQRY='UPDATE COM_CC50051 SET  RESIGNREMARKS=ISNULL('''+ @REASON +''',''''),RESIGNTYPE=''' + @RESIGNTYPE +''',RESIGNSTATUS='''+ @RESIGNSTATUS +''' '  
  
   IF(isnull(@RESIGNDATE,'')<>'')  
    SET @STRQRY=@STRQRY +' ,DORESIGN=CONVERT(FLOAT,CONVERT(DATETIME,'''+ CONVERT(NVARCHAR,@RESIGNDATE) +'''))'  
   IF(isnull(@TENTATIVEDATE,'')<>'')  
    SET @STRQRY=@STRQRY +', DOTENTRELIEVE=CONVERT(FLOAT,CONVERT(DATETIME,'''+ CONVERT(NVARCHAR,@TENTATIVEDATE) +'''))'  
   IF(isnull(@REDATE,'')<>'' AND @RESIGNTYPE<>'Pending')  
   BEGIN  
    SET @STRQRY=@STRQRY +', DORELIEVE=CONVERT(FLOAT,CONVERT(DATETIME,'''+ CONVERT(NVARCHAR,@REDATE) +'''))'  
  
    -- UPDATING USER STATUS TO IN-ACTIVE W.E.F DateOfRelieving  
    DECLARE @EmpUserID BIGINT  
    SELECT @EmpUserID=ISNULL(UserID,0) From ADM_Users WITH(NOLOCK) Where UserName=(Select Code FROM COM_CC50051 WITH(NOLOCK) WHERE NodeID=@EMPNODE)  
    IF(@EmpUserID IS NOT NULL AND @EmpUserID<>0)  
    BEGIN  
     INSERT INTO [COM_CostCenterStatusMap] ([CostCenterID],[NodeID],[Status],FromDate,ToDate,[CreatedBy],[CreatedDate])  
     SELECT 7,@EmpUserID,2,CONVERT(int,DATEADD(day,1,@REDATE)),NULL,'admin',convert(float,getdate())  
    END  
  
   END  
      
  END   
  ELSE  
  BEGIN  
   SET @STRQRY=@STRQRY +' UPDATE COM_CC50051 SET DORESIGN=NULL,DOTENTRELIEVE=NULL,DORELIEVE=NULL,RESIGNREMARKS=NULL,RESIGNTYPE=NULL,RESIGNSTATUS=NULL '  
  END  
  
  SET @STRQRY=@STRQRY + ' WHERE NODEID='''+ CONVERT(NVARCHAR,@EMPNODE) +''''  
  --PRINT @STRQRY  
  EXEC (@STRQRY)  
 END  
 ELSE IF (@COSTCENTERID=40065)--REJOIN FROM VACATION  
 BEGIN  
  IF((SELECT COUNT(*) FROM INV_DOCDETAILS WITH(NOLOCK) WHERE DOCID=@DOCID )>0) --AND STATUSID=369
  BEGIN  
     
   DECLARE @tID BIGINT  
   SELECT TOP 1 @tID= CONVERT(BIGINT,dcAlpha1)  
   FROM INV_DocDetails a WITH(NOLOCK)   
   JOIN COM_DocTextData d WITH(NOLOCK) ON d.InvDocDetailsID=a.InvDocDetailsID  
   WHERE a.CostCenterID=40061 and a.StatusID=369  
   AND ISNUMERIC(dcAlpha1)=1  
  
   SELECT @FROMDATE=CONVERT(DATETIME,TD.DCALPHA1),@TODATE=CONVERT(DATETIME,TD.DCALPHA2) FROM COM_DOCTEXTDATA TD INNER JOIN INV_DOCDETAILS ID ON TD.INVDOCDETAILSID=ID.INVDOCDETAILSID AND ID.DOCID=@DOCID  
  
   IF(@tID=CONVERT(BIGINT,@TENTATIVEDATE))  
   BEGIN  
    UPDATE TD SET TD.dcAlpha1=CONVERT(DATETIME,@REDATE) FROM COM_DOCTEXTDATA TD INNER JOIN COM_DOCCCDATA CC ON TD.INVDOCDETAILSID=CC.INVDOCDETAILSID AND CC.dcCCNID51=@EMPNODE  
    INNER JOIN INV_DOCDETAILS ID ON TD.INVDOCDETAILSID=ID.INVDOCDETAILSID And ID.CostCenterId=40072 AND ISDATE(TD.DCALPHA2)=1 AND ISDATE(TD.DCALPHA3)=1  
    AND CONVERT(DATETIME,TD.DCALPHA2)=CONVERT(DATETIME,@FROMDATE) AND CONVERT(DATETIME,TD.DCALPHA3)=CONVERT(DATETIME,@TODATE)  
   END  
   ELSE  
   BEGIN  
    UPDATE TD   
    SET TD.dcAlpha15=CONVERT(DATETIME,@REDATE)   
    FROM COM_DOCTEXTDATA TD   
    JOIN COM_DOCCCDATA CC ON TD.INVDOCDETAILSID=CC.INVDOCDETAILSID   
    JOIN INV_DOCDETAILS ID ON TD.INVDOCDETAILSID=ID.INVDOCDETAILSID   
    WHERE ID.DocumentType=62 AND CC.dcCCNID51=@EMPNODE AND CC.dcCCNID52=CONVERT(BIGINT,@TENTATIVEDATE)  
    AND ISDATE(TD.DCALPHA4)=1 AND ISDATE(TD.DCALPHA5)=1  
    AND CONVERT(DATETIME,TD.DCALPHA4)=CONVERT(DATETIME,@FROMDATE) AND CONVERT(DATETIME,TD.DCALPHA5)=CONVERT(DATETIME,@TODATE)  
   END  
  
  END   
 END  
END  
END  
GO
