USE PACT2C222
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spSVC_GetVehicleYears]
	@MAKEID [bigint] = 0,
	@MODELID [bigint] = 0
WITH ENCRYPTION, EXECUTE AS CALLER
AS
begin  
CREATE TABLE #TBLTEMP(ID INT IDENTITY(1,1),[STARTYEAR] NVARCHAR(300),[ENDYEAR] NVARCHAR(300))  
INSERT INTO #TBLTEMP  
  select StartYear,EndYear from SVC_Vehicle where MakeID=@MAKEID AND ModelID=@MODELID  
  
DECLARE @I INT,@COUNT INT,@START BIGINT,@ENDYEAR BIGINT,@J INT,@TEMPCOUNT INT  

SELECT @I=1,@COUNT=COUNT(*) FROM #TBLTEMP  
 CREATE TABLE #TBL(ID INT IDENTITY(1,1),[Y] NVARCHAR(300))  
WHILE @I<=@COUNT  
BEGIN  
SELECT @START=[STARTYEAR],@ENDYEAR=[ENDYEAR] FROM #TBLTEMP WHERE ID=@I --FOR START YEAR  
IF((SELECT COUNT(*) FROM #TBL WHERE [Y]=@START)=0)  
BEGIN  
if(@START is not null and @START <> '')  
INSERT INTO #TBL VALUES (@START)  
END  
 
if(@ENDYEAR is not null and @ENDYEAR = '0')  
BEGIN
SELECT   @ENDYEAR=YEAR(GETDATE())
END
  
 WHILE @START<@ENDYEAR  
 BEGIN  
 IF((SELECT COUNT(*) FROM #TBL WHERE [Y]=@START)=0)  
 BEGIN  
  if(@START is not null and @START <> '')  
  INSERT INTO #TBL VALUES (@START)  
 END   
 SET @START=@START+1  
 END  
  --FOR END YEAR  
IF((SELECT COUNT(*) FROM #TBL WHERE [Y]=@ENDYEAR)=0)  
BEGIN  
if(@ENDYEAR is not null and @ENDYEAR <> '')  
INSERT INTO #TBL VALUES (@ENDYEAR)  
END  
  
  
  
SET @I=@I+1  
END  


SELECT * FROM #TBL ORDER BY Y  desc   
DROP TABLE #TBL  
DROP TABLE #TBLTEMP  
  
end  
GO
